name: Merge dev to main and change files

on:
  push:
    branches:
      - dev

jobs:
  merge_and_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge dev into main
        run: git checkout main
        run: git merge --no-ff origin/dev -m "Merge dev into main"
        run: git push
