name: Merge dev to main and change files

on:
  push:
    branches:
      - dev

jobs:
  merge_and_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout main branch
        run: git checkout main

      - name: Merge dev into main
        run: git merge --no-ff origin/dev -m "Merge dev into main"

      - name: Change files from dev to prod
        run: |
          sed -i 's/dev/prod/g' src/store/index.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Change files from dev to prod"
          git push
