name: Merge dev to main and change files

on:
  push:
    branches:
      - dev

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Merge dev into main
        run: 
             git merge --no-ff origin/dev -m "Merge dev into main"
             git push
