name: Merge dev to main and change files

on:
  push:
    branches:
      - dev

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # with:
        #   fetch-depth: 2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge master back to dev
        run: |
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff dev -m "Auto-merge master back to dev"
            git push

      - name: Edit index.js
        run: |
            sed -i "s/mode: 'dev'/mode: 'prod'/" src/store/index.js
     
      - name: Commit and push changes
        run: |
          git diff --quiet || { git add . && git commit -m "Update mode to prod" && git push; }

      # - name: Build project
      #   run: |
      #     npm i
      #     npm run build
      - name: Install Packages and Build Application 
        run: |
          npm ci
          npm run build

      - name: Copy files to Windows server
        uses: appleboy/ssh-action@master
        with:
          host: "52.220.173.180"
          username: "administrator"
          password: "Grade5-ship-Line8-blue3"
          port: "33488"
          script: |
            $source = "dist"
            $destination = "C:\inetpub\test_auto_deploy"
            New-Item -ItemType Directory -Path $destination -ErrorAction SilentlyContinue
            Copy-Item -Path $source -Destination $destination -Recurse