name: Merge dev to main and deploy

on:
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge master back to dev
        run: |
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff dev -m "Auto-merge master back to dev"
            git push

      - name: Edit index.js
        run: |
          (Get-Content "src\store\index.js") -replace "mode: 'dev'", "mode: 'prod'" | Set-Content "src\store\index.js"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update mode to prod"
          git push

      - name: Build project
        run: |
          npm install
          npm run build

      # - name: Install Packages and Build Application 
      #   run: |
      #     npm ci
      #     npm run build

      - name: Deploy to IIS
        shell: cmd
        run: |
          xcopy /s /y .\dist C:\inetpub\CPOC-AIMS\Frontend