name: Merge dev to main and change files

on:
  push:
    branches:
      - dev

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push
