name: Merge dev to main and change files

on:
  push:
    branches:
      - dev

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
      - name: Merge master back to dev
        run: |
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff dev -m "Auto-merge master back to dev"
            git push
      - name: Edit index.js
        run: |
            sed -i "s/mode: 'dev'/mode: 'prod'/" src/store/index.js
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "Changes found"
          git diff --quiet || exit 1

      - name: Commit and push changes
        if: steps.git-check.outcome == 'success'
        run: |
          git add .
          git commit -m "Update mode to prod"
          git push