name: Merge dev to main and change files

on:
  push:
    branches:
      - dev

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge master back to dev
        run: |
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff dev -m "Auto-merge master back to dev"
            git push

      - name: Edit index.js
        run: |
            sed -i "s/mode: 'dev'/mode: 'prod'/" src/store/index.js
     
      - name: Commit and push changes
        run: |
          git diff --quiet || { git add . && git commit -m "Update mode to prod" && git push; }

      - name: Build project
        run: |
          npm run build

      - name: Copy files to Windows server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_SERVER_HOST }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          port: ${{ secrets.WINDOWS_SERVER_PORT }}
          script: |
            $source = "build"
            $destination = "C:/testing"
            New-Item -ItemType Directory -Path $destination -ErrorAction SilentlyContinue
            Copy-Item -Path $source -Destination $destination -Recurse